#!/bin/bash

gpu_ip=$(awsip sandbox-gpu-joep)
cpu_ip=$(awsip sandbox-cpu-joep)


config_fragments_folder='/home/jbarmentlo/.ssh/config_fragments/'
gpu_filename="${config_fragments_folder}sandbox_gpu_joep"
cpu_filename="${config_fragments_folder}sandbox_cpu_joep"
base_config_filename="${config_fragments_folder}base_config"
config_tmp_filename="${config_fragments_folder}tmp_config"

echo "Deleting ${config_tmp_filename}"
rm -f $config_tmp_filename

if [ $gpu_ip != 'null' ]
then
    sed "s/HOST_PLACEHOLDER/${gpu_ip}/" $gpu_filename >> $config_tmp_filename
    echo "GPU sandbox has been added to hosts"

else
    echo "GPU sandbox is off and has not been added to hosts"
fi

if [ $cpu_ip != 'null' ]
then
    sed "s/HOST_PLACEHOLDER/${cpu_ip}" $cpu_filename >> $config_tmp_filename
    echo "CPU sandbox has been added to hosts"
else
    echo "CPU sandbox is off and has not been added to hosts"
fi

echo "Saving .ssh/config file to .ssh/config.old"
# echo "If you want to add your own config to the autogenerated aws config. Add it to ${base_config_filename}"
cat /home/jbarmentlo/.ssh/config > /home/jbarmentlo/.ssh/config.old

echo "applying config changes"

cat $base_config_filename > /home/jbarmentlo/.ssh/config

echo -e "\n##################################################" >> /home/jbarmentlo/.ssh/config
echo    "#         Auto Generated aws ssh config          #" >> /home/jbarmentlo/.ssh/config
echo -e "##################################################\n" >> /home/jbarmentlo/.ssh/config

cat $config_tmp_filename >> /home/jbarmentlo/.ssh/config

rm -f $config_tmp_filename
